name: gitars_app
description: Аккорды, песни и инструменты для гитариста.
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  html: ^0.15.4
  http: ^1.2.1
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  record: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - lib/acords/
    - lib/images/

  uses-material-design: true
